
name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      - name: Build Docker image
        run: docker build -t lungsc-ml .
      - name: Run preprocessing
        run: docker run lungsc-ml Rscript scripts/preprocess.R
      - name: Train ML model
        run: docker run lungsc-ml python3 scripts/train_ml_model.py
